

services:
  mysql:
    image: mysql:5.7
    container_name: ramazan_mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: apirequestpanel
      MYSQL_USER: ramazan_user
      MYSQL_PASSWORD: ramazan_pass
      MYSQL_ROOT_PASSWORD: rootpass123
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - admin_net
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -prootpass123 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 15
      start_period: 20s

  app:
    build: .
    container_name: ramazan_app
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/apirequestpanel?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Baku
      SPRING_DATASOURCE_USERNAME: ramazan_user
      SPRING_DATASOURCE_PASSWORD: ramazan_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - admin_net

networks:
  admin_net:
    driver: bridge

volumes:
  mysql_data:
